### ISSUE TITLE
Unable to get the value of constant field of .NET type

### ISSUE THREAD

**Issue by Taritsyn** [paulbartrum/jurassic#5]
During executing the following code:

	var jsEngine = new ScriptEngine
	{
		EnableExposedClrTypes = true
	};
	jsEngine.SetGlobalValue("Math2", typeof(Math));

	object result = jsEngine.Evaluate("Math2.PI");
	
Error occurs:

	Unhandled Exception: System.NotSupportedException: Specified method is not supported.
	   at System.Reflection.MdFieldInfo.get_FieldHandle()
	   at Jurassic.Compiler.DynamicILGenerator.GetToken(FieldInfo field) in c:\temp\jurassic\Jurassic\Compiler\Emit\ILGenerator\DynamicILGenerator.cs:line 476
	   at Jurassic.Compiler.DynamicILGenerator.LoadField(FieldInfo field) in c:\temp\jurassic\Jurassic\Compiler\Emit\ILGenerator\DynamicILGenerator.cs:line 1885
	   at Jurassic.Compiler.FieldGetterBinder.GenerateStub(ILGenerator generator, Int32 argumentCount) in c:\temp\jurassic\Jurassic\Compiler\Binders\FieldBinders.cs:line 91
	   at Jurassic.Compiler.Binder.CreateDelegateCore(Int32 argumentCount) in c:\temp\jurassic\Jurassic\Compiler\Binders\Binder.cs:line 148
	   at Jurassic.Compiler.Binder.CreateDelegate(Int32 argumentCount) in c:\temp\jurassic\Jurassic\Compiler\Binders\Binder.cs:line 99
	   at Jurassic.Compiler.Binder.Call(ScriptEngine engine, Object thisObject, Object[] arguments) in c:\temp\jurassic\Jurassic\Compiler\Binders\Binder.cs:line 74
	   at Jurassic.Library.ClrFunction.CallLateBound(Object thisObject, Object[] arguments) in c:\temp\jurassic\Jurassic\Library\Function\ClrFunction.cs:line 179
	   at Jurassic.Library.PropertyAccessorValue.GetValue(ObjectInstance thisObject) in c:\temp\jurassic\Jurassic\Library\Object\PropertyAccessorValue.cs:line 52
	   at Jurassic.Library.ObjectInstance.InlineGetPropertyValue(String name, Int32& cachedIndex, Object& cacheKey) in c:\temp\jurassic\Jurassic\Library\Object\ObjectInstance.cs:line 298
	   at eval(ScriptEngine , Scope , Object )
	   at Jurassic.Compiler.EvalMethodGenerator.Execute() in c:\temp\jurassic\Jurassic\Compiler\MethodGenerator\EvalMethodGenerator.cs:line 119
	   at Jurassic.ScriptEngine.Evaluate(ScriptSource source) in c:\temp\jurassic\Jurassic\Core\ScriptEngine.cs:line 621
	   at Jurassic.ScriptEngine.Evaluate(String code) in c:\temp\jurassic\Jurassic\Core\ScriptEngine.cs:line 572
	   ...

**Comment by paulbartrum** [comment]
EnableExposedClrTypes doesn't work properly right now, I'm afraid.  I am not a big fan of this feature, and will likely ditch it in the upcoming version 3.
